- fpga_interchange/chip_info.py
- fpga_interchange/nextpnr_emit.py
Do generate constids.txt for easy constid debugging.
> Move strings into BBA and don't generate constids.inc.

- fpga_interchange/chip_info.py
- fpga_interchange/device_resources.py
- fpga_interchange/populate_chip_info.py
- fpga_interchange/yosys_json.py
I need to refactor this, but this is good enough to emit a working constant network.
> Add constant network to FPGA interchange BBA

- fpga_interchange/populate_chip_info.py
Found during some early testing of interchange export from prjoxide
> Fix case of a tile without any wires

- fpga_interchange/chip_info.py
- fpga_interchange/device_resources.py
- fpga_interchange/parameter_definitions.py
- fpga_interchange/populate_chip_info.py
- fpga_interchange/yosys_json.py
Peer changes are https://github.com/Xilinx/RapidWright/pull/141 and https://github.com/SymbiFlow/fpga-interchange-schema/pull/19
> Convert Yosys binary strings to the format specified from the device database.

- setup.py
Increment version in preparation to cut a `v0.0.3` release.
> Increment version in setup.py

- fpga_interchange/capnp_utils.py
A grammatical update in documented code
> tech-doc-update

- .github/workflows/ci.yml
- fpga_interchange/interchange_capnp.py
- tests/example_netlist.py
> interchange_capnp: fix enum assignment when reading phys netlist

- test_data/nexus_device_config.yaml
For the WIP counter example, in conjunction with gatecat/prjoxide#5 (don't merge quite yet)
> nexus: Update device_config.yaml

- fpga_interchange/fasm_generators/xc7.py
> fasm: bram: fix wrong indentation

- fpga_interchange/fasm_generators/xc7.py
This PR fixes fasm generation around:
- BRAMS:
- features were conflicting between different BRAMs.
- wrong bus range for INIT params.
- FFs: 
- It seems that the FFSYNC feature is active only for the FDRE FF type.
TODO:
> fasm: xc7: fix FFSYNC and BRAM features

- fpga_interchange/device_resources.py
- fpga_interchange/fasm_generators/generic.py
- fpga_interchange/fasm_generators/xc7.py
- fpga_interchange/interchange_capnp.py
- fpga_interchange/physical_netlist.py
This PR fixes https://github.com/SymbiFlow/python-fpga-interchange/issues/75.
It requires https://github.com/SymbiFlow/fpga-interchange-schema/pull/56.
> Add site to pseudo tile pips

- fpga_interchange/chip_info.py
- fpga_interchange/populate_chip_info.py
- fpga_interchange/yosys_json.py
Depends on SymbiFlow/fpga-interchange-schema#42
This only contains the macro content currently, it is _not_ outputting the exception and parameter mapping rules yet.
> Add macro content to chipdb

- fpga_interchange/chip_info.py
- test_data/xcup_constraints.yaml
- test_data/xcup_device_config.yaml
- test_data/xcup_luts.yaml
This currently gets as far as creating a chipdb ~~(although a RapidWright with verification patched out is needed due to https://github.com/Xilinx/RapidWright/issues/194). nextpnr is currently hitting an assertion failure when using the chipdb which I'm investigating.~~
> UltraScale+ device config

- fpga_interchange/fasm_generators/xc7.py
> fasm: xc7: fix slice routing bels

- fpga_interchange/fasm_generators/xc7.py
This PR add support for BRAM36 in xc7 fasm.
Also it fixes some bugs found on the way, like incorrect regexes 
> Add support for RAMB36 cells

- fpga_interchange/fasm_generators/generic.py
- fpga_interchange/fasm_generators/xc7.py
This adds features for:
- ISERDES
- OSERDES
- IDELAY
> fasm: xc7: add IOI tiles

- test_data/xcup_device_config.yaml
> device data: xcup: disable PPIPs through LUTs

- fpga_interchange/yosys_json.py
This fixes a bug for which, if a floating point parameter is instantiated as a decimal in verilog, the resulting parameter `stringText` will not be in the form specified in the interchange format, but as a decimal, and not as a floating point.
E.g.:
```
PLLE2_ADV #(
...
.CLKOUT0_PHASE (90),
...
) pll ( ... );
```
This results in yosys generating a bitvector representation for the value, instead of a floating point string.
This PR handles this case and correctly transforms bitvectors in floating points strings where needed.
> netlist: fix floating point parameter when converting yosys to netlist

- fpga_interchange/fasm_generators/nexus/nexus.py
> fasm: nexus: fix call to fill_pip_features

- fpga_interchange/chip_info.py
- fpga_interchange/device_resources.py
- fpga_interchange/fasm_generators/xc7/xc7.py
- fpga_interchange/interchange_capnp.py
- fpga_interchange/logical_netlist.py
- fpga_interchange/populate_chip_info.py
- test_data/series7_constraints.yaml
- test_data/series7_device_config.yaml
This PR adds python code to created clusters definitions from macros.
> Convert macros to clusters for better placement

- fpga_interchange/compare_timings.py
> Fix backslash escape by converting any series of them into single backslash

- fpga_interchange/fasm_generators/xc7/xc7.py
> fasm: xc7: add w7/8 used mux

- fpga_interchange/populate_chip_info.py
> clusters: macro: disable other cells in same site with macro clusters

- fpga_interchange/compare_timings.py
> Fix regex strings

- fpga_interchange/testarch_generators/generate_testarch.py
> testarch: add more arguments to make the testarch gen more flexible

- fpga_interchange/testarch_generators/device_resources_builder.py
> Fix testarch generator's primLib

- fpga_interchange/compare_timings.py
- fpga_interchange/testarch_generators/device_resources_builder.py
- fpga_interchange/testarch_generators/generate_testarch.py
- test_data/gen_luts.yaml
Fixes to:
* compare_timings.py
* testarch generator
* testarch gen_luts
> Various fixes

- fpga_interchange/testarch_generators/generate_testarch.py
> testarch: fix LUT init param

- fpga_interchange/testarch_generators/generate_testarch.py
This PR adds a command-line option to the testarch generator which disables the `FFMUX` forcing any FF inputs to require LUT-thrus. This option is needed for testing VPR LUT-thru support in interchange arch.
> An option to disable FFMUX in the testarch

- fpga_interchange/testarch_generators/device_resources_builder.py
- fpga_interchange/testarch_generators/generate_testarch.py
This PR is to add multiple BELs in the same site that can implement the same cell. This is to test whether the cell bel mapping is properly working.
> testarch: add multiple bels in the same site

- fpga_interchange/nextpnr_emit.py
- fpga_interchange/testarch_generators/generate_testarch.py
The suffix is needed to have multiple BBA files generated in the same directory.
> Added optional suffix for BBA files

- fpga_interchange/testarch_generators/generate_testarch.py
> testarch: fix IOB cell bel mapping

- test_data/xcup_device_config.yaml
Add macro expansions for LUT-RAMs.
> Macro clusters for xcup LUT-RAMs

- fpga_interchange/testarch_generators/device_resources_builder.py
This PR adds support for writing tile PIPs with pseudo cells (PPIPs).
> Device resource builder - pseudo-PIPs

- fpga_interchange/testarch_generators/device_resources_builder.py
This PR exposes all constant handling entities in the device resources builder.
> Constant handling in device resources builder

- fpga_interchange/yosys_json.py
When using the `splitnets` pass Yosys preserves `offset` of each resulting net while it appends the index `[<index>]` part to its name. This confuses the conversion script and results in index duplication as it considers net literaly named eg. `cnt[3]` as 3rd bit of the bus `cnt` and stores it as `cnt[3][3]`.
This PR addresses this unwanted behavior by not considering 1-bit nets nets named `<name>[<index>]` with offset==index as part of a bus.
> Bus net handling in Yosys JSON to netlist conversion
