- .github/workflows/ci.yml
- .github/workflows/test.sh
- .gitignore
- Makefile
- fpga_interchange/annotations.py
- fpga_interchange/capnp_utils.py
- fpga_interchange/compare.py
- fpga_interchange/convert.py
- fpga_interchange/converters.py
- fpga_interchange/field_cache.py
- fpga_interchange/interchange_capnp.py
- fpga_interchange/json_support.py
- fpga_interchange/rapidyaml_support.py
- fpga_interchange/yaml_support.py
- requirements.txt
- setup.py
- tests/test_converters.py
This is an initial attempt at using capnp annotations to enable automated textual format conversions. I've implemented a prototype that converts to/from capnp, YAML, and JSON, all as defined by the capnp schema.
Remaining work:
> Add capnp converters to and from YAML and JSON.

- .github/workflows/ci.yml
- .github/workflows/test.sh
- fpga_interchange/convert.py
- requirements.txt
- setup.py
I've also relaxed the dependency on PyYAML and Rapidyaml as optional features.  `fpga_interchange.convert` will generate an error if the user requests support and it isn't loaded.
> Update schema path now that schema has it's own repository.

- fpga_interchange/chip_info.py
- fpga_interchange/nextpnr.py
- fpga_interchange/populate_chip_info.py
Two important new constant network changes:
- Site ports are now marked with their signal type, e.g.
signal/gnd/vcc.  This is so that the site router can determine if a
site port can be used to route a specific net.
- Best constant net name is now available.
> Add local site inverter data, along with some constant network meta.

- test_data/nexus_device_config.yaml
Currently the only bel/cell being fully exported are LUTs so that's all this rather unexciting config has for now. But it should be enough to set up build scripts in nextpnr for nexus support.
> nexus: Add stub device_config.yaml

- fpga_interchange/add_prim_lib.py
- fpga_interchange/interchange_capnp.py
This allows the device database to be patched with the Yosys cell library (which is the source of truth for primitive cells in prjoxide).
Although there is a bit of duplication with `yosys_json.py`, I have decided to keep this codepath largely separate because of the significant differences between importing a netlist and importing blackboxes.
cc @litghost ; I don't seem to have permission to request a review.
> Add tool for importing primLibs from Yosys JSON

- fpga_interchange/device_resources.py
- fpga_interchange/yosys_json.py
This is important for some vendor tools (e.g. Vivado) that expect
parameters to have a value even if the value is simply the default.
> Set default parameters on logical netlists from Yosys JSON.

- fpga_interchange/add_prim_lib.py
- fpga_interchange/interchange_capnp.py
- fpga_interchange/logical_netlist.py
- fpga_interchange/yosys_json.py
When nesting LogicalNetlist.strList in another schema, the root strList
is used.
Fixes #47
> Have add_prim_lib use DeviceResources.strList when patching.

- fpga_interchange/populate_chip_info.py
Otherwise the LUT mapper ends up failing in a hard-to-debug way (memory corruption) if you get things wrong.
I'm adding the check here as I presume the lack of assertions and use of `operator[]` instead of `at()` inside the nextpnr LUT mapper code is because LUT manipulation is (currently) on the placement hot path.
> chip_info: Bounds check LUT indices

- fpga_interchange/yosys_json.py
These come from Yosys as encoded strings so we don't need to first parse them as binary.
> yosys_json: Leave cHex and cBinary parameters alone

- fpga_interchange/nextpnr_emit.py
- fpga_interchange/populate_chip_info.py
- test_data/series7_device_config.yaml
BUFGCTRL route-throughs are currently broken, and need to be disabled.
This stops them from being exported to nextpnr.
Hotfix for the issue discussed in #57
> Enable disabling of route-thru PIPs for BUFGCTRL

- fpga_interchange/chip_info_utils.py
- fpga_interchange/constraints/tool.py
- fpga_interchange/device_resources.py
- fpga_interchange/fasm_generator.py
- fpga_interchange/fasm_generators/generic.py
- fpga_interchange/fasm_generators/xc7.py
- fpga_interchange/parameter_definitions.py
- setup.py
At the moment, we need to still come up with a good enhancement of the schema to support FASM features annotations to be added to the DeviceResources for a more data-driven approach.
With the current initial implementation, FASM features a quite fixed, and, even though they can still be made more data-driven, some specialization may be required to handle different devices families, hence the adoption of a inheritance based generator, such that different families can change the implementation or have more detailed functions to add and deal with some possibly complex FASM annotations.
This initial implementation is able to generate valid FASM outputs for the `const_wire` and `wire` from nextpnr which do work on HW.
This PR was opened mainly to get an early review of the progress.
TODO:
- …
> Initial FASM generator

- fpga_interchange/__init__.py
- fpga_interchange/fasm_generator.py
- fpga_interchange/fasm_generators/generic.py
- fpga_interchange/fasm_generators/xc7.py
- setup.py
This commit also:
- slightly changes the way the physical LUT init is generated and fixes a few comments
- adds an origin line to the output FASM file to know which version was used to generate a specific FASM output
> fasm: explicit fasm file argument

- fpga_interchange/device_resources.py
I'm working on doing some analysis of site types and common routing patterns to look at future approaches to massively speed up site routing using code generation, and these fields seem like they'll be useful for doing more site analysis.
> device_resources: Adding more site type fields

- fpga_interchange/parameter_definitions.py
This fix addresses a problem found when debugging the RAM test from [nextpnr](https://github.com/YosysHQ/nextpnr/tree/master/fpga_interchange/examples/tests/ram).
The problem is that the `textValues` in the netlist corresponding to the INIT parameter of the RAMB cell were not padded, e.g. as follows:
```
- &id172
name: ram.ram.0.0.0
propMap:
entries:
- key: module_not_derived
textValue: 00000000000000000000000000000001
- key: src
textValue: '/usr/local/bin/../share/yosys/xilinx/xc7_brams_map.v:296.5-320.4'
- key: INITP_00
textValue: "256'h4450"
- key: INITP_01
textValue: "256'h0"
- key: INITP_02
textValue: "256'h0"
- key: INITP_03
textValue: "256'h0"
- key: INITP_04
textValue: "256'h0"
- key: INITP_05
textValue: "256'h0"
- key: INITP_06
textValue: "256'h0"
- key: INITP_07
textValue: …
```
> parameters: add padding when encoding integers 

- fpga_interchange/nextpnr_emit.py
- fpga_interchange/populate_chip_info.py
- test_data/series7_device_config.yaml
This comes in handy primarily for debugging purposes and addresses https://github.com/SymbiFlow/python-fpga-interchange/issues/71
> device_config: allow disabling specific cell to bel mappings

- fpga_interchange/fasm_generators/generic.py
- fpga_interchange/fasm_generators/xc7.py
- fpga_interchange/interchange_capnp.py
- fpga_interchange/parameter_definitions.py
- fpga_interchange/physical_netlist.py
This PR adds support for writing RAMB18 features from a physical and logical netlists.
It has been tested with the ram design.
I believe there are enough handling cases at the moment to start the work towards a better generalization of the FASM feature handling, by expanding the device resources database in order to hold information on how to write FASM features for the various parameters, routing bels, pips, etc.
> fasm: add RAMB18 features generation

- fpga_interchange/chip_info.py
- fpga_interchange/device_resources.py
- fpga_interchange/populate_chip_info.py
When we are happy, it'd be great to get this merged and a release cut so I can move onto globals and also rebase the other lower priority chipdb affecting PRs on top of it.
> chip_info: Add wire types to chipdb

- fpga_interchange/chip_info.py
- fpga_interchange/populate_chip_info.py
- test_data/nexus_device_config.yaml
- test_data/series7_device_config.yaml
For now this info is being stored in `device_config.yaml`, when things are a bit more stable it might make sense to move it (and perhaps some of the other `device_config` stuff to the schema itself).
This'll need another release cut once merged.
> chip_info: Add more info for global placement/routing

- test_data/series7_device_config.yaml
BUFRs sites are allowed to be routed through for some non-clock-related signals, which might not be ideal (even though it is actually allowed).
These route-thrus can be temporarily disabled, to force the router to properly use general interconnect.
In addition, other FF cells are added to the exclusion list from the `cell <-> bel` mapping, mainly for FASM generation reasons.
> device config: xc7: filter out cells2bel and routethrus

- fpga_interchange/populate_chip_info.py
This improves the contract checking for #34, which does need to be fixed properly at some point, but at least makes a breach of this contract result in a Python assertion failure rather than a nextpnr segfault (leading to the fun debugging https://github.com/gatecat/prjoxide/commit/e62452795d6ec8a4d0207df88b8d49d0bed0207e)
> Assert that (0, 0) really is empty

- fpga_interchange/populate_chip_info.py
- setup.py
It appears that, for xilinx devices, the `(0, 0)` tile contains one wire named `DUMMYFOO`. This PR fixes the assertion to not fail if all wires in the `null_tile_type` are dummy in reality.
This PR also syncs the setup version with the current tag.
> populate chip info: fix assertion

- fpga_interchange/fasm_generator.py
- fpga_interchange/fasm_generators/generic.py
- fpga_interchange/fasm_generators/nexus.py
Currently, this is very minimal FASM generation for the Nexus (routing and IO), enough to build a wire between a button and an LED.
Remaining issues for a blinky:
> Nexus FASM generation

- .gitignore
- fpga_interchange/chip_info.py
- fpga_interchange/nextpnr.py
- fpga_interchange/populate_chip_info.py
- test_data/series7_device_config.yaml
This PR is based on https://github.com/SymbiFlow/python-fpga-interchange/pull/70 and aims at redefining the BEL chaining to make it more flexible and allow also the definition of clusters to guide nextpnr placement.
It mainly detaches from using the schema, and directly adds information to the nextpnr chipdb.
It still is marked as WIP as it needs more iterations to get to a stable and reviewable state.
> Add interchange clustering definition

- fpga_interchange/fasm_generators/nexus.py
- test_data/nexus_device_config.yaml
Please note that this currently sits on top of #92 and #96.
With latest prjoxide master and YosysHQ/nextpnr#728, it is possible to build and run a simple BRAM test on hardware (LIFCL-40-EVN) successfully.
> nexus: Basic FASM generator support for BRAM

- fpga_interchange/fasm_generators/generic.py
- fpga_interchange/fasm_generators/luts.py
- fpga_interchange/fasm_generators/nexus.py
- fpga_interchange/fasm_generators/xc7.py
There are some features which can be inferred based on physical bel pins, for instance the `CIN` pin of the `CARRY4`.
Longer-term, I believe these information will much better reside in the device database, so that no special handling is required.
In addition this PR does:
- add CARRY4 FASM output
- move LUT mapper to another file
> fasm: add bel pins features handling

- .github/workflows/ci.yml
- .github/workflows/testarch_device.sh
- Makefile
- fpga_interchange/constraints/model.py
- fpga_interchange/converters.py
- fpga_interchange/fasm_generators/xc7.py
- fpga_interchange/interchange_capnp.py
- fpga_interchange/testarch_generators/device_resources_builder.py
- fpga_interchange/testarch_generators/generate_testarch.py
- test_data/gen_device_config.yaml
This is a very WIP code that in the end should allow to easily define a test FPGA architecture with timings. Currently it generates and writes site types and tile types, no alternative site types supported.
> Python code for generating and writing test architecture

- fpga_interchange/populate_chip_info.py
The check that there are no wires in this tile (other than dummy wires) is more relevant in any case, so there's no need any more to so strict about the name of the tile type.
This is needed for UltraScale+ support, where the 0,0 tile is `HPIO_TERM_L_DA6_TERM_T_FT` but still empty.
> chip_info: Don't require 0,0 tile type to be exactly NULL

- fpga_interchange/chip_info.py
- fpga_interchange/populate_chip_info.py
- test_data/series7_device_config.yaml
This PR adds an additional information to the clusters to allow out of site expansions when looking for a valid BEL.
> cluster: add field to allow clusters in different sites

- fpga_interchange/device_resources.py
- fpga_interchange/fasm_generators/generic.py
- fpga_interchange/fasm_generators/xc7.py
- fpga_interchange/fasm_generators/xc7_iobs.py
Adds support for:
- all supported IOSTANDARDS, DRIVE and SLEW combinations present in prjxray-db
- missing CARRY features
> fasm: xc7: add handling of IOBs and complete carry features

- fpga_interchange/fasm_generators/xc7.py
This PR fixes routing issues inside SLICEM sites, SRL muxes and some other signals related to distributed memory weren't properly handled. Also IO SING tiles had issue. These tiles only have 1 site, and its bits depend on tile position in the fabric grid.
For tiles that their Y mod 50 is zero, site uses bits for site Y0 but if Y mod 50 is 49 then site is configured using Y1 bits.
https://github.com/SymbiFlow/prjxray/blob/cb5f2a30633bf0d3ac91a9b5802790ac1da86736/fuzzers/005-tilegrid/generate_full.py#L357-L365
> Fix fasm CLBLM and SING tiles

- fpga_interchange/parameter_definitions.py
Possibly related to https://github.com/Xilinx/RapidWright/issues/216, some booleans can potentially be stored in different formats.
This PR is to allow having different version of the Boolean string format, so to decode the integer correctly.
> params: add other valid boolean strings when converting str to int

- test_data/series7_device_config.yaml
> Turn off pseudoPIPs going through LUT6 bels in Xilinx 7-series

- fpga_interchange/interchange_capnp.py
For some larger designs, the nesting limit of the route branches is reached, causing a failure while reading the physical netlist. This PR increases the limit
> interchange: increase nesting limit

- fpga_interchange/testarch_generators/device_resources_builder.py
- fpga_interchange/testarch_generators/generate_testarch.py
This PR adds the following:
- parameter definition for the LUT cell
- merge IPAD and OPAD in a single PAD (similarly to how it is usually seen in series7 and other arches). This is to better understand and implement the IO handler in the VTR interchange development.
> Testarch generator: add LUT param definition and use single PAD

- fpga_interchange/testarch_generators/device_resources_builder.py
- fpga_interchange/testarch_generators/generate_testarch.py
- test_data/gen_device_config.yaml
This PR adds more complexity to the cell bel mappings in the test architecture, so to better test on the VTR interchange implementation and start closing the gap between a test architecture and a real one.
Additionally, there are changes that fix the variables and functions style naming to the recently added LUT definitions.
> testarch: add more complex cell bel mappings

- fpga_interchange/testarch_generators/generate_testarch.py
This PR adds complexity to the IO sites, allowing for more complex cases, more similar to real devices.
For instance, it generates three different IO types:
- InOut
- Input only
- Output only
Additionally, this PR adds another SLICE for each CLB
> Improve IO pads complexity handling

- fpga_interchange/testarch_generators/device_resources_builder.py
- fpga_interchange/testarch_generators/generate_testarch.py
This PR fixes an issue with the testarch generator / device resources builder so that it is now possible to have multiple LUT elements within the same site type.
> Allow multiple LUT elements in site type

- .github/workflows/ci.yml
https://github.com/Xilinx/RapidWright/commit/d422b0d2bf8b9ebd3e16592703d583565997cb9e removed exucution of `compile` target under `update_jars`. The `compile` target generates `bin/rapidwright_classpath.sh` which is required later.
> CI: [Rapidwright] Run make compile before make update_jars

- test_data/xcup_device_config.yaml
Required to route PLLE4s to slices through through global buffers.
> Enable BUFCE route-through for US+ devices and increase max_hops for global buffers

- fpga_interchange/testarch_generators/device_resources_builder.py
- fpga_interchange/testarch_generators/generate_testarch.py
This PR fixes the test architecture generation by:
- removing the cell to bel mapping content for constant cells
- adding proper package information complete with speed grades
> Test arch packages

- fpga_interchange/yosys_json.py
Relaxed net naming, consider only nets named `<name>[<index>]` and ignore others.
> Hotfix for #159

- requirements.txt
- setup.py
The CI for the older version fails. It passes after this change.
> Pin pycapnp library to a working version

- fpga_interchange/add_prim_lib.py
This fixes the following error that is thrown: 
```
Traceback (most recent call last):                                                                                                           
File "/data/interchange/fpga-interchange-tests/env/conda/envs/fpga-interchange/lib/python3.7/runpy.py", line 193, in _run_module_as_main   
"__main__", mod_spec)                                                                                                                    
File "/data/interchange/fpga-interchange-tests/env/conda/envs/fpga-interchange/lib/python3.7/runpy.py", line 85, in _run_code              
exec(code, run_globals)                                                                                                                  
File …
```
> yosys_json: fix prim lib import
